# Site settings
title: hello baby
tag_text: ctt & li 
description: miss u
url: "http://ctt.li"
baseurl: ""

font-awesome-include: false # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]


permalink: pretty
permalink: /:title/
