# Site settings
title: hello baby
tag_text: ctt & li 
description: never gonna give you up
url: "http://ctt.li"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
